"use client";

import {
    Badge,
    Box,
    Flex,
    Heading,
    Text
} from "@chakra-ui/react";

interface Props {
    generatedBy: string;
    project?: {
        projectName?: string | null;
        auditName?: string | null;
        auditType?: string | null;
        description?: string | null;
        configuredChecks?: number;
    };
}

export default function ProjectHeader({
    generatedBy,
    project
}: Props) {

    return (
        <>
            <Flex
                justify="space-between"
                align="center"
                mb={6}
            >
                <Box>
                    <Heading color="blue.900">
                        AI HITL Summary
                    </Heading>

                    <Text
                        color="gray.600"
                        mt={1}
                    >
                        Gemini Analysis & Audit Performance
                    </Text>
                </Box>

                <Badge
                    px={3}
                    py={2}
                    borderRadius="md"
                    bg={
                        generatedBy === "gemini"
                            ? "green.100"
                            : "orange.100"
                    }
                    color={
                        generatedBy === "gemini"
                            ? "green.700"
                            : "orange.700"
                    }
                >
                    {generatedBy === "gemini" ? "Generated by Gemini" : "Local Summary"}
                </Badge>
            </Flex>

            <Box
                bg="blue.900"
                color="white"
                p={5}
                borderRadius="md"
                mb={5}
            >
                <Flex
                    justify="space-between"
                    wrap="wrap"
                    gap={4}
                >
                    <Box maxW="700px">
                        <Heading size="lg">
                            {project?.projectName ||
                                "Quality Audit"}
                        </Heading>

                        <Text mt={2}>
                            {project?.auditName ||
                                project?.auditType}
                        </Text>

                        {project?.description && (
                            <Text
                                mt={2}
                                fontSize="sm"
                                opacity={0.8}
                            >
                                {project.description}
                            </Text>
                        )}
                    </Box>

                    <Box textAlign="right">
                        <Text fontSize="sm">
                            Configured Checks
                        </Text>

                        <Heading>
                            {project?.configuredChecks || 0}
                        </Heading>
                    </Box>
                </Flex>
            </Box>
        </>
    );
}